//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_SQLBuilder
{
    using System;
    using System.Collections.Generic;
    
    public partial class insert_table
    {
        public int id { get; set; }
        public int fk_project { get; set; }
        public string table { get; set; }
        public int order { get; set; }
    
        public virtual project project { get; set; }
    }
}
