//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_SQLBuilder
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.insert_table = new HashSet<insert_table>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string destiny_db_type { get; set; }
        public string origin_host { get; set; }
        public string origin_port { get; set; }
        public string origin_db { get; set; }
        public string origin_schema { get; set; }
        public string origin_user { get; set; }
        public string destiny_host { get; set; }
        public string destiny_port { get; set; }
        public string destiny_db { get; set; }
        public string destiny_schema { get; set; }
        public string destiny_user { get; set; }
        public string origin_db_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insert_table> insert_table { get; set; }
    }
}
