//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_SQLBuilder
{
    using System;
    using System.Collections.Generic;
    
    public partial class select_field
    {
        public int id { get; set; }
        public int fk_insert_table { get; set; }
        public string selected_field { get; set; }
        public string column { get; set; }
        public string default_value { get; set; }
    
        public virtual insert_table insert_table { get; set; }
    }
}
